sudo: required
services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/face-attr-pred-frontend -f ./frontend/docker/prod.Dockerfile ./frontend
  - docker build -t $DOCKER_USERNAME/face-attr-pred-backend -f ./backend/Dockerfile ./backend
  - docker build -t $DOCKER_USERNAME/face-attr-pred-nginx -f ./reverse_proxy/Dockerfile ./reverse_proxy

script:
  - docker build -t $DOCKER_USERNAME/face-attr-pred-frontend-test -f ./frontend/docker/dev.Dockerfile ./frontend

after_success:
  # Log in to the Docker CLI
  - echo "$DOCKER_LOGIN_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/face-attr-pred-frontend
  - docker push $DOCKER_USERNAME/face-attr-pred-backend
  - docker push $DOCKER_USERNAME/face-attr-pred-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: docker-loginapp
  env: DockerLoginapp-env
  bucket_name: elasticbeanstalk-ap-south-1-679022722124
  bucket_path: docker-loginapp
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY
