sudo: required
services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/face-attr-pred-frontend -f ./frontend/docker/prod.Dockerfile ./frontend
  - docker build -t $DOCKER_USERNAME/face-attr-pred-backend -f ./backend/Dockerfile ./backend
  - docker build -t $DOCKER_USERNAME/face-attr-pred-nginx -f ./reverse_proxy/Dockerfile ./reverse_proxy

after_success:
  # Log in to the Docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_USERNAME/face-attr-pred-frontend
  - docker push $DOCKER_USERNAME/face-attr-pred-backend
  - docker push $DOCKER_USERNAME/face-attr-pred-nginx
