version: "3"

networks:
  zonic:

services:
  frontend:
    image: node:13.14
    #    build:
    #      context: ./frontend
    container_name: frontend
    working_dir: /app
    stdin_open: true
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules
    ports:
      - 3000:80
    networks:
      - zonic
    entrypoint: ["npm"] # command would start with this
    command: ["start"] # CAN be overwritten

  backend:
    container_name: backend
    stdin_open: true
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/src
    ports:
      - 7777:5000
    networks:
      - zonic
    depends_on:
      - frontend

  nginx:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      # - precip-service
    ports:
      - 80:80
    networks:
      - zonic
