version: "3"
networks:
  zonic:

services:
  frontend:
    image: node:13.14
    build:
      context: ./frontend/
      dockerfile: ./docker/dev.Dockerfile
    container_name: frontend
    stdin_open: true
    volumes:
      - ./frontend:/app/
      - ./frontend/node_modules
    ports:
      - 3000:3000
    working_dir: /app
    networks:
      - zonic
    entrypoint: ["npm"] # command would start with this
    command: ["start"] # CAN be overwritten

  backend:
    container_name: backend
    stdin_open: true
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/src
      - ./backend/torch-cache:/root/.cache/torch/
    # ports:
    #   - 7777:5000
    networks:
      - zonic
    depends_on:
      - frontend
    # command: gunicorn --reload wsgi:app -b 0.0.0.0:5000 --timeout=500

  nginx:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    networks:
      - zonic
